---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui
  namespace: flux-system
spec:
  interval: 15m
  chart:
    spec:
      chart: open-webui
      version: "*"                 
      sourceRef:
        kind: HelmRepository
        name: open-webui
        namespace: flux-system
  install:
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
      remediateLastFailure: true
  driftDetection:
    mode: warn
  targetNamespace: open-webui