apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: helmrelease-values.patch.yaml
    target:
      kind: HelmRelease
      name: nginx-gateway-fabric
      namespace: flux-system
