---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-dynamo-crds
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: dynamo-crds
      version: "0.6.0"
      sourceRef:
        kind: HelmRepository
        name: nvidia-dynamo
        namespace: flux-system
      interval: 1h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: warn
  targetNamespace: default
