apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      group: gateway.networking.k8s.io
      version: v1
      kind: Gateway
      name: public
      namespace: nginx-gateway
    path: gateway-patch.yaml