---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-gpu-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: gpu-operator
      version: "v25.3.4" 
      sourceRef:
        kind: HelmRepository
        name: nvidia-gpu-operator
        namespace: flux-system
  interval: 1h
  install:
    crds: Create
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
      remediateLastFailure: true
  driftDetection:
    mode: warn
  targetNamespace: nvidia-gpu-operator




