---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vllm-stack
  namespace: flux-system
spec:
  interval: 20m
  timeout: 15m
  chart:
    spec:
      chart: vllm-stack
      version: "*"                 # pin/adjust as you prefer
      sourceRef:
        kind: HelmRepository
        name: vllm-production-stack
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
      remediateLastFailure: true
  driftDetection:
    mode: warn
  targetNamespace: vllm-production-stack