apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  values:
    fullnameOverride: cert-manager
    config:
      apiVersion: "controller.config.cert-manager.io/v1alpha1"
      kind: "ControllerConfiguration"
      enableGatewayAPI: true
    installCRDs: true