---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-models
  namespace: ollama
spec:
  resources:
    requests: 
      storage: 20Gi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: openwebui-data
#   namespace: open-webui
# spec:
#   resources:
#     requests: 
#       storage: 30Gi
