---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vllm-production-stack
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/vllm-production-stack/overlay/staging-gpu
  dependsOn:
    - name: app-sources-helm
    - name: infra-app-namespace
    # - name: infra-pvc
# ---     
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: apps-open-webui
#   namespace: flux-system
# spec:
#   interval: 10m
#   timeout: 20m
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   path: ./apps/open-webui/overlay/staging
#   dependsOn:
#     - name: apps-ollama 
