apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nvidia-dynamo-crds
  namespace: flux-system
spec:
  interval: 10m
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system          
  path: ./infrastructure/crds/nvidia-dynamo/base