apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nvidia-gpu-operator
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/controllers/nvidia-gpu-operator/overlays/staging
  # dependsOn:
  #   - name: nginx-gateway-fabric         