---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: nginx-gateway-fabric
  namespace: flux-system
spec:
  interval: 10m
  url: oci://ghcr.io/nginx/charts/nginx-gateway-fabric
