---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-gateway-fabric
  namespace: flux-system
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: nginx-gateway-fabric
    namespace: flux-system
  install:
    crds: Create
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
      remediateLastFailure: true
  driftDetection:
    mode: warn
  targetNamespace: nginx-gateway
  # values:
  #   nginx:
  #     service:
  #       type: NodePort