# ---
# apiVersion: source.toolkit.fluxcd.io/v1
# kind: OCIRepository
# metadata:
#   name: external-dns
#   namespace: flux-system
# spec:
#   interval: 1h
#   url: oci://registry-1.docker.io/bitnamicharts/external-dns
