---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  chart:
    spec:
      chart: external-dns
      version: "*"  # Replace with the desired version
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system 
  interval: 12h
  install:
    crds: Create
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
      remediateLastFailure: true
  driftDetection:
    mode: warn
  targetNamespace: external-dns