---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hf-token
  namespace: default
spec:
  encryptedData:
    HUGGING_FACE_HUB_TOKEN: AgAT7DxZi5ZgEzYIaeNSGrlvhtmvg9EJXae9GndXrCbeMAGyt113C/mjST/KUMnGCsesgugzqA6giCkwBRPFt1SAmu8Qkjq3SOZXZRqrPc38FtFI/SaxXTiTqTWcibNL3YjzTecJdCWu7SYHcKVFrQtEsRS7QskdMw1/gJ7iDmlKfVvjh23QjMPKWRAQNPwM6tZWD/dnUMjOSPIaRSKGhQkI03pcZTu+jzYd5lbnFd3K4rBfudxGwF1u++UAc+9Ujm8/Y81zOBy30dhcD60J6JvyQH+MOgMy6RMoHEHjFRTpNmirkX7m+4MBi011qon46GPdqGUTmdEorfmk7uOUKH/BbGNKywv19KQ5GwL1hY5V/jo+kxzqc26mgTwTkwGULqrAFyFNaMAw0ZXhodc5/u/P9KutWKOxgOwq7GDFqjgtmMVoChYr4uC2LaXdtFuTqg3tv/8WCNOwSYVz5H12nPH1b8AZxVL8VDZQKh7Gb+td8rPJOlInC7Zni7ckaJVUveCz9GXm4/ggWZCgxOifRKFasvjGGHe3k3UB1X34RHcwrnOkzs69ILs/OLkFS3VKG7IoK8ygWrc3UDF7DspiscppK9nDP0ZzTPdXwysqiFxjw+8Qn4OFcj6C9Vx0L8prygq92inQMKE43UExC+wSPDPaG/1fPdrq2Ki+vCRNA//6iG6nRGsthS4r3u5tIlYE1AiqmNrXxVFCUZ3gmJhEwR/zSCwYdBDCmP1TF3dKD8AGasKyO5Ly
  template:
    metadata:
      name: hf-token
      namespace: default
